Traceback (most recent call last):
  File "/usr/local/Cellar/letsencrypt/0.4.2/libexec/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.2', 'console_scripts', 'letsencrypt')()
  File "/usr/local/Cellar/letsencrypt/0.4.2/libexec/lib/python2.7/site-packages/letsencrypt/cli.py", line 1953, in main
    args = prepare_and_parse_args(plugins, cli_args)
  File "/usr/local/Cellar/letsencrypt/0.4.2/libexec/lib/python2.7/site-packages/letsencrypt/cli.py", line 1645, in prepare_and_parse_args
    return helpful.parse_args()
  File "/usr/local/Cellar/letsencrypt/0.4.2/libexec/lib/python2.7/site-packages/letsencrypt/cli.py", line 1247, in parse_args
    self.handle_csr(parsed_args)
  File "/usr/local/Cellar/letsencrypt/0.4.2/libexec/lib/python2.7/site-packages/letsencrypt/cli.py", line 1280, in handle_csr
    _process_domain(parsed_args, d)
  File "/usr/local/Cellar/letsencrypt/0.4.2/libexec/lib/python2.7/site-packages/letsencrypt/cli.py", line 1825, in _process_domain
    domain = le_util.enforce_domain_sanity(domain)
  File "/usr/local/Cellar/letsencrypt/0.4.2/libexec/lib/python2.7/site-packages/letsencrypt/le_util.py", line 339, in enforce_domain_sanity
    raise errors.ConfigurationError("Requested domain {0} is not a FQDN".format(domain))
ConfigurationError: Requested domain gratus.u57ysrrpfx.us-west-2.elasticbeanstalk.com/ is not a FQDN
